name: Auto Release CSI-Powerflex
on:
  workflow_dispatch:
  repository_dispatch:
    types: [auto-driver-module-release-workflow]

jobs:
  csm-release:
    runs-on: ubuntu-latest

    steps:
      - name: Set GPG Private Key as an Environment Variable
        run: echo "GPG_PRIVATE_KEY=${{ secrets.CSM_GPG_PRIVATE_KEY }}" >> $GITHUB_ENV

      - name: Trigger Reusable Workflow
        uses: meggm/common-github-actions-test/.github/workflows/csm-release-driver-module.yaml@main
        with:
          version: "minor"
          images: "csi-vxflexos"
        secrets: inherit
