name: Auto Release CSI-Powerflex
on:
  workflow_dispatch:
  repository_dispatch:
    types: [auto-driver-module-release-workflow]

jobs:
  csm-release:
    runs-on: ubuntu-latest
    env:
      GPG_PRIVATE_KEY: ${{ secrets.CSM_GPG_PRIVATE_KEY }}  # Set the secret as an environment variable

    uses: meggm/common-github-actions-test/.github/workflows/csm-release-driver-module.yaml@main
    with:
      version: "minor"
      images: "csi-vxflexos"
    secrets: inherit
