name: Auto Release CSI-Powerflex

on:
  workflow_dispatch:
  repository_dispatch:
    types: [auto-driver-module-release-workflow]

jobs:
  read-secrets:
    runs-on: ubuntu-latest
    outputs:
      gpg_key: ${{ steps.set-gpg-key.outputs.gpg_key }}
    steps:
      - name: Sanitize and Set GPG Private Key as Output
        id: set-gpg-key
        run: |
          sanitized_key=$(echo "${{ secrets.CSM_GPG_PRIVATE_KEY }}" | tr -d '\r\n')
          echo "::set-output name=gpg_key::$sanitized_key"

  csm-release:
    needs: read-secrets
    uses: meggm/common-github-actions-test/.github/workflows/dummy-test.yaml@main
    with:
      version: "minor"
      images: "csi-vxflexos"
    secrets:
      GPG_KEY: ${{ needs.read-secrets.outputs.gpg_key }}





