name: Auto Release CSI-Powerflex

on:
  workflow_dispatch:
  repository_dispatch:
    types: [auto-release-workflow]

jobs:
  csm-release:
    uses: dell/common-github-actions/.github/workflows/csm-release-driver-module.yaml@meggm/test-oneclick
    with:
      version: "minor"
      images: "csi-vxflexos"
      gpg_key: ${{ github.event.client_payload.gpg_key }}
    secrets: inherit  




