name: Auto Release CSI-Powerflex

on:
  workflow_dispatch:
  repository_dispatch:
    types: [auto-driver-module-release-workflow]

jobs:
  csm-release:
    uses: meggm/common-github-actions-test/.github/workflows/csm-release-driver-module.yaml@main
    with:
      version: "minor"
      images: "csi-vxflexos"
      gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      gpg_passphrase: ${{ secrets.GPG_PASSPHRASE }}
    secrets: inherit  




