name: Auto Release CSI-Powerflex

on:
  workflow_dispatch:
  repository_dispatch:
    types: [auto-driver-module-release-workflow]

jobs:
  read-secrets:
    runs-on: ubuntu-latest
    outputs:
      gpg_key:
        value: ${{ steps.set-gpg-key.outputs.gpg_key }}
    steps:
      - name: Sanitize and Set GPG Private Key as an Output
        id: set-gpg-key
        run: |
          sanitized_key=$(echo "${{ secrets.CSM_GPG_PRIVATE_KEY }}" | tr -d '\r')
          echo "::set-output name=gpg_key::${sanitized_key}"

  csm-release:
    needs: read-secrets
    uses: meggm/common-github-actions-test/.github/workflows/csm-release-driver-module.yaml@main
    with:
      version: "minor"
      images: "csi-vxflexos"
      gpg_key: ${{ needs.read-secrets.outputs.gpg_key }}
    secrets: inherit


