name: Auto Release CSI-Powerflex

on:
  workflow_dispatch:
  repository_dispatch:
    types: [auto-driver-module-release-workflow]

jobs:
  csm-release:
    uses: meggm/common-github-actions-test/.github/workflows/csm-release-driver-module.yaml@main
    with:
      version: "minor"
      images: "csi-vxflexos"
      #gpg_key: ${{ github.event.client_payload.gpg_key }}
    secrets: inherit  




